## Bitcoin Price Prediction (30 days in advance)

In [19]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR

In [37]:
btc = pd.read_csv("bitcoin_dataset.csv")
btc.head()

Date        Price
0  5/23/2019  7881.846680
1  5/24/2019  7987.371582
2  5/25/2019  8052.543945
3  5/26/2019  8673.215820
4  5/27/2019  8805.778320

In [38]:
btc.drop(['Date'],1,inplace=True)

C:\Users\kmbmh\AppData\Local\Temp\ipykernel_7656\4147944305.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  btc.drop(['Date'],1,inplace=True)


In [39]:
days_to_pred = 30
btc['Prediction'] = btc[['Price']].shift(-days_to_pred)
btc.head()

Price   Prediction
0  7881.846680  10701.69141
1  7987.371582  10855.37109
2  8052.543945  11011.10254
3  8673.215820  11790.91699
4  8805.778320  13016.23145

In [40]:
#no predcitions yet
btc.tail()

Price  Prediction
362  9729.038086         NaN
363  9522.981445         NaN
364  9081.761719         NaN
365  9182.577148         NaN
366  9180.045898         NaN

In [41]:
#Indenpent dataset
#The data frame -> numpy array 
x = np.array(btc.drop(['Prediction'],1))
x = arr[:len(btc)-days_to_pred]
x

C:\Users\kmbmh\AppData\Local\Temp\ipykernel_7656\938984437.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  x = np.array(btc.drop(['Prediction'],1))


array([[ 7881.84668 ],
       [ 7987.371582],
       [ 8052.543945],
       [ 8673.21582 ],
       [ 8805.77832 ],
       [ 8719.961914],
       [ 8659.487305],
       [ 8319.472656],
       [ 8574.501953],
       [ 8564.016602],
       [ 8742.958008],
       [ 8208.995117],
       [ 7707.770996],
       [ 7824.231445],
       [ 7822.023438],
       [ 8043.951172],
       [ 7954.12793 ],
       [ 7688.077148],
       [ 8000.32959 ],
       [ 7927.714355],
       [ 8145.857422],
       [ 8230.923828],
       [ 8693.833008],
       [ 8838.375   ],
       [ 8994.488281],
       [ 9320.352539],
       [ 9081.762695],
       [ 9273.521484],
       [ 9527.160156],
       [10144.55664 ],
       [10701.69141 ],
       [10855.37109 ],
       [11011.10254 ],
       [11790.91699 ],
       [13016.23145 ],
       [11182.80664 ],
       [12407.33203 ],
       [11959.37109 ],
       [10817.15527 ],
       [10583.13477 ],
       [10801.67773 ],
       [11961.26953 ],
       [11215.4375  ],
       [109

In [42]:
# Dependent data set
y = np.array(btc['Prediction'])
y = y[:-days_to_pred]
y

array([10701.69141 , 10855.37109 , 11011.10254 , 11790.91699 ,
       13016.23145 , 11182.80664 , 12407.33203 , 11959.37109 ,
       10817.15527 , 10583.13477 , 10801.67773 , 11961.26953 ,
       11215.4375  , 10978.45996 , 11208.55078 , 11450.84668 ,
       12285.95801 , 12573.8125  , 12156.5127  , 11358.66211 ,
       11815.98633 , 11392.37891 , 10256.05859 , 10895.08984 ,
        9477.641602,  9693.802734, 10666.48242 , 10530.73242 ,
       10767.13965 , 10599.10547 , 10343.10645 ,  9900.767578,
        9811.925781,  9911.841797,  9870.303711,  9477.677734,
        9552.860352,  9519.145508,  9607.423828, 10085.62793 ,
       10399.66895 , 10518.17481 , 10821.72656 , 10970.18457 ,
       11805.65332 , 11478.16895 , 11941.96875 , 11966.40723 ,
       11862.93652 , 11354.02441 , 11523.5791  , 11382.61621 ,
       10895.83008 , 10051.7041  , 10311.5459  , 10374.33887 ,
       10231.74414 , 10345.81055 , 10916.05371 , 10763.23242 ,
       10138.04981 , 10131.05566 , 10407.96484 , 10159.

In [129]:
#Split data: 20% testing & 80% training
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size = 0.2) 
days_to_pred_array = np.array(btc.drop(['Prediction'],1))[-days_to_pred:]
days_to_pred_array

C:\Users\kmbmh\AppData\Local\Temp\ipykernel_7656\2838283874.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  days_to_pred_array = np.array(btc.drop(['Prediction'],1))[-days_to_pred:]


array([[7550.900879],
       [7569.936035],
       [7679.867188],
       [7795.601074],
       [7807.058594],
       [8801.038086],
       [8658.553711],
       [8864.766602],
       [8988.59668 ],
       [8897.46875 ],
       [8912.654297],
       [9003.070313],
       [9268.761719],
       [9951.518555],
       [9842.666016],
       [9593.896484],
       [8756.430664],
       [8601.795898],
       [8804.477539],
       [9269.987305],
       [9733.72168 ],
       [9328.197266],
       [9377.013672],
       [9670.739258],
       [9726.575195],
       [9729.038086],
       [9522.981445],
       [9081.761719],
       [9182.577148],
       [9180.045898]])

### Machine Learning Model

In [134]:
#Suppor Vector Machine (Regression)
svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.00001)
svr_rbf.fit(xtrain, ytrain)

SVR(C=1000.0, gamma=1e-05)

### Testing the model (SVM)

In [136]:
# predicted values
svm_prediction = svr_rbf.predict(xtest)
svm_prediction

array([ 9532.1794334 ,  9404.18628251,  8893.588316  ,  9369.60936795,
        8865.72692378,  7489.28550467,  9363.1391874 ,  9528.14885084,
        9549.51611609,  9543.56993145,  8654.25552228,  8233.5383581 ,
        9064.6718405 ,  8203.4539414 ,  8974.70854868,  7735.70927475,
        7915.65645369,  7552.69734399, 10218.51686863,  9556.98903262,
        8443.247588  , 10266.55078983, 10222.24713498,  8746.11187265,
        9559.42674969,  8279.08667808,  9399.48715205,  8369.37131175,
        8205.74997213,  8262.09416616, 10264.05040464,  8396.35123437,
        7488.494482  ,  9828.93086611,  8954.23342086,  8201.55520608,
       11182.46604312,  9301.53623681,  7987.72023917, 10934.68839513,
        8665.24982942,  8208.235906  , 10410.7622646 ,  9096.74878416,
        9876.92318192,  9001.09132089, 10101.86046705,  8309.50004011,
        7767.73393758,  8201.6634226 ,  9324.95609896,  8693.19380033,
        7793.80797355,  9928.59981319,  8215.44206419,  9760.73721883,
      

In [137]:
ytest

array([ 6733.387207,  7564.345215,  8706.245117, 11961.26953 ,
        8897.46875 ,  7569.629883,  7243.134277,  7217.427246,
        9412.612305, 10345.81055 ,  7879.071289, 10360.54688 ,
        7275.155762, 10019.7168  ,  8657.642578,  7257.665039,
        7292.995117,  7556.237793, 10343.10645 , 10141.99609 ,
        6985.470215, 10916.05371 , 10970.18457 ,  9726.575195,
        9889.424805,  9477.641602,  7493.48877 ,  9842.666016,
        7973.20752 ,  7514.671875,  9811.925781,  5392.314941,
        7761.243652, 10085.62793 ,  9261.104492,  8620.566406,
        9552.860352, 11392.37891 ,  9293.521484, 10334.97461 ,
        8864.766602,  8586.473633, 10353.30273 ,  6606.776367,
        7218.816406,  8228.783203, 10441.27637 ,  8293.868164,
        8787.786133, 10181.6416  ,  8804.880859,  8192.494141,
        6867.527344,  7302.089355,  5200.366211,  7642.75    ,
        8151.500488,  9519.145508,  8205.369141,  8205.939453,
        5225.629395,  9670.739258, 12156.5127  , 11523.

In [138]:
# Predictions for the next 30 days
svm_prediction = svr_rbf.predict(days_to_pred_array)

In [139]:
#Actual price for bitcoin for last 30 days
pred=pd.DataFrame()
pred['Price'] = btc['Price'].tail(days_to_pred)
pred['Prediction']=svm_prediction
pred

Price   Prediction
337  7550.900879  7850.211113
338  7569.936035  7916.891064
339  7679.867188  8622.738147
340  7795.601074  9492.532658
341  7807.058594  9560.548219
342  8801.038086  9417.721385
343  8658.553711  9494.282596
344  8864.766602  9124.585317
345  8988.596680  8317.994176
346  8897.468750  8928.385189
347  8912.654297  8830.359564
348  9003.070313  8223.177983
349  9268.761719  7555.109007
350  9951.518555  8251.104895
351  9842.666016  8239.605086
352  9593.896484  8313.720096
353  8756.430664  9530.335504
354  8601.795898  9343.684798
355  8804.477539  9405.634281
356  9269.987305  7557.611555
357  9733.721680  8260.093838
358  9328.197266  7714.681503
359  9377.013672  7879.684295
360  9670.739258  8292.416189
361  9726.575195  8263.379763
362  9729.038086  8262.226755
363  9522.981445  8264.933463
364  9081.761719  7779.924721
365  9182.577148  7498.842914
366  9180.045898  7501.203848